### ISSUE TITLE
[PlayerEx][Multiplayer] Players can continue to use level up on server when datapack limits level

### ISSUE THREAD

**Issue by Vitalcord** [CleverNucleus/PlayerEx#106] opened 2023-01-29 00:17 UTC
Version:
3.5.0 and 3.5.1

Observed:
While using the provided examples in the FAQ section to make a datapack that restricts player max level to 20, the datapack works on singleplayer worlds. When on a server with the datapack, the player's level stops progressing at 20, but they can still press the level up button and are rewarded with additional skill points. Even attributes, which in the datapack were capped at 20, can have a player put skill points in them, though this will not increase the stat (button is not greyed out, still selectable.)

Repro Rate: 3/3

Steps to Reproduce:
 - Create a datapack using this code to limit level cap https://clevernucleus.github.io/playerex-1.18.2_faq.html#:~:text=%7B%0A%20%20%20%20%22fallbackValue%22%3A%200.0%2C%0A%20%20%20%20%22minValue%22%3A%200.0%2C%0A%20%20%20%20%22maxValue%22%3A%2050.0%2C%0A%20%20%20%20%22incrementValue%22%3A%200.0%2C%0A%20%20%20%20%22translationKey%22%3A%20%22playerex.attribute.name.level%22%2C%0A%20%20%20%20%22stackingBehaviour%22%3A%20%22FLAT%22%0A%7D 
 - Apply to an online server
 - Log into server
 - Grant yourself as much XP as possible
 - Rapidly level up to 20 and continue to press Level Up
 - Observe you still get skill points

**Comment by Vitalcord** [comment] 2023-01-29 00:52
Additionally, when using this pack on a single player world, and then loading into the server, the issue is not present. But if they load a singleplayer world without the datapack and then return to the server the issue is present again.

**Comment by Vitalcord** [comment] 2023-01-29 01:38
After some additional testing, this issue appears to only be present with Data Attributes v1.4.1.

**Comment by CleverNucleus** [comment] 2023-01-29 11:57
Hi there,
I've looked into this - it appears the latest release of Data Attributes has broken PlayerEx. I will hopefully output a fix in the coming week.
Thanks.

**Comment by CleverNucleus** [comment] 2023-02-02 12:25
Root cause is [this issue](https://github.com/CleverNucleus/Data-Attributes/issues/28); therefore, closing this issue now as it is a duplicate.

**Closed by CleverNucleus** 2023-02-02 12:25 UTC
Labels: bug
