### ISSUE TITLE
No level etc

### ISSUE THREAD

**Issue by GulliUlli** [CleverNucleus/PlayerEx#108] opened 2023-02-02 17:10 UTC
hi,
i have a new issue. im using the newest version on my server, but if i join (or anyone else) to the server, i unter attributes only the "+"
no name of attribute no level etc. and my char's states are like lvl 0.

then i leave the server and start a singleplayer world. all works fine and i go back to my server and then i works fine too. this i have todo every time i start the game.

**Comment by DcZipPL** [comment] 2023-02-02 19:52
Same issue here. I see only + buttons. The issue occurs on latest and older versions of the mod.

**Comment by CleverNucleus** [comment] 2023-02-02 20:24
Duplicate of [this issue](https://github.com/CleverNucleus/Data-Attributes/issues/28).

**Closed by CleverNucleus** 2023-02-02 20:24 UTC
