### ISSUE TITLE
v2.0.3 error with BetterEnd

### ISSUE THREAD

**Issue by natsistd** [CleverNucleus/PlayerEx#14] opened 2021-07-04 11:13 UTC
![2021-07-04_06 51 26](https://user-images.githubusercontent.com/68826224/124382357-04945580-dc95-11eb-9c6a-80ccf9f69194.png)

I get the following error when opening/creating a world on Minecraft with the latest version of PlayerEx (v2.0.3) and BetterEnd:

> "Errors in currently selected datapacks prevented the world from loading. You can either try to load it with only the vanilla data pack ("safe mode"), or go back to the title screen and fix it manually."

This error does not seem occur when using the previous version of PlayerEx (v2.0.2).

I did notice this in the log:

`Caused by: java.lang.ClassCastException: ru.betterend.item.EndAttribute cannot be cast to com.github.clevernucleus.playerex.impl.attribute.IClampedEntityAttribute`

**Comment by CleverNucleus** [comment] 2021-07-04 13:53
Hi there,
I see what the problem is; I'll fix it asap.
Thanks for letting me know.

**Comment by CleverNucleus** [comment] 2021-07-08 11:46
This is fixed now.

**Closed by CleverNucleus** 2021-07-08 11:46 UTC
