### ISSUE TITLE
Error Entity Ticking when using PlayerEx (do the mod edit Bat or something)

### ISSUE THREAD

**Issue by ardissaps** [CleverNucleus/PlayerEx#70] opened 2022-06-26 01:37 UTC
Crash Log :
https://pastebin.com/xDuPuQ0N

Latest Log :
https://pastebin.com/AG8JY0CP

Crashy : 
https://crashy.net/cxzkw4d8AA1i4uCtZreo?code=16wa5r

Launcher Log :
https://paste.atlauncher.com/view/7c30fdc5-4dd6-4677-9d37-7358de62d683

It is easily ignored by [Error Entity Remover](https://modrinth.com/mod/erroring-entity-remover), but as stated by mod author that should be only last resort. Also if I force to use it sure it will not crash but make egg spawn does not work as it is removed immediately after spawn. When I disable Error Entity Remover mods, afters hours looking for what causing I found removing PlayerEx fixed the problem. I hope it will be fixed soon as your mods is really good but I deactiving temporaly it as it cause trouble with detailed mentioned above.

**Comment by ardissaps** [comment] 2022-06-26 01:49
I am testing if that possible problem with [AttributeFix](https://www.curseforge.com/minecraft/mc-mods/attributefix).

**Comment by CleverNucleus** [comment] 2022-06-26 12:55
Hi there,
Looking at the error log, this crash is caused by Port Lib, and is a duplicate of [this](https://github.com/CleverNucleus/Data-Attributes/issues/16). An update on their end (Port Lib) is being pushed that prevents the crash (fixing the actual bug that causes this is for me to solve), however I expect that this change is still propagating through all the dependents.

Thanks for the report; I'm closing this issue now.

**Closed by CleverNucleus** 2022-06-26 12:55 UTC

**Comment by ardissaps** [comment] 2022-06-26 23:32
> Port Lib,

Which mod that bundle port libt?

**Comment by CleverNucleus** [comment] 2022-06-26 23:45
No problem, Create contains the embedded library porting_lib (Port Lib).
