### ISSUE TITLE
crash fabric create-mc 1.18.2_v0.4.1 +631

### ISSUE THREAD

**Issue by Colddo118** [CleverNucleus/PlayerEx#64] opened 2022-06-22 15:30 UTC

**Comment by CleverNucleus** [comment] 2022-06-23 09:17
Hi there,
This is not really a useful issue. Please provide the crash log.
Thanks.

**Comment by CleverNucleus** [comment] 2022-06-23 09:57
No worries; I'll look into the issue.
Thank you for reporting it.

**Comment by CleverNucleus** [comment] 2022-06-23 23:52
This behaviour has been found to be caused by Data Attributes - of which a duplicate issue now exists [here](https://github.com/CleverNucleus/Data-Attributes/issues/15). Closing this issue for that reason.

**Closed by CleverNucleus** 2022-06-23 23:52 UTC
Labels: bug
