### ISSUE TITLE
Game freezes with PlayerEx on joining a world

### ISSUE THREAD

**Issue by TheRealDanini** [CleverNucleus/PlayerEx#114] opened 2023-03-07 02:27 UTC
As the title says, when loading a world with PlayerEx my game gets stuck on the joining world screen. I would provide logs but they do not seem to be generated and in some cases it even softlocks my pc to where I am unable to alt f4 the game. If I had to guess either PlayerEx has a conflict (I do not believe this would be the case) or the dependency's for PlayerEx has a conflict. (also do not believe this would be the case either)

One time however when alt f4'ing my game my launcher gave me an exit code that is related to out of memory issues, I have my launcher set to give Minecraft 6GB's of ram so it is hard to believe that this mod would be the cause of an out of memory issue
although I was never able to obtain a crash log, there are some things we do know, first off is the memory problem (maybe there is a memory leak or some issue like mod conflicts) and the second is that this is on the 1.19.2 fabric build of the mod. Not sure if any of that information would help, if I am ever able to obtain a crash log or any information I will post it here

**Comment by CleverNucleus** [comment] 2023-03-08 20:18
Does this happen for just one particular world? Or any time you create a new world? Does this happen with *just* PlayerEx and its dependencies installed?

**Comment by TheRealDanini** [comment] 2023-03-09 00:29
It seems to mostly happen when PlayerEx is installed making it so I am unable to join a world, if I have PlayerEx without any dependencies fabric gives me an error. as for a profile with just PlayerEx I could test that and if it works on that profile it could be a mod conflict, but as to what mod in perticular that would be an issue as my game half softlocks windows (only escapable with locking windows and logging in), meaning that the crashlogs are not generated and that makes it harder to determine what caused the game to freeze on joining a world.

**Comment by CleverNucleus** [comment] 2023-03-09 16:37
>It seems to mostly happen when PlayerEx

*Mostly?* Are there instances when it is not freezing?

>so I am unable to join a world

All worlds? Just one in particular? Can you create new worlds?
>PlayerEx without any dependencies fabric gives me an error.

I meant just PlayerEx **and** its dependencies i.e., PlayerEx, Data Attributes and Fabric API.

**Comment by TheRealDanini** [comment] 2023-03-09 18:37
> _Mostly?_ Are there instances when it is not freezing?
There was a few instances where it did load, but mostly it froze on joining world
> All worlds? Just one in particular? Can you create new worlds?
It seemed to be all worlds, even newly created ones
> I meant just PlayerEx **and** its dependencies i.e., PlayerEx, Data Attributes and Fabric API.
I tested it on a new profile with only PlayeEx and the dependencies and it loads worlds, from this alone I believe it is a mod conflict, but without a crashlog this will be hard to determine what is causing the game to freeze. I could send a list of mods that I was using when this happened

**Comment by TheRealDanini** [comment] 2023-03-09 18:53
This is all of the mods that I have installed on my profile

`--All mods are their fabric versions for 1.19.2--

-CameraOverhaul 1.4.0
-Do A Barrel Roll 2.6.2
-Alloy Forgery 2.0.19
-Crawling mod 0.11.1
-Patchouli 1.19.2-77
-Things for trinkets 0.3.0
-owo-lib
-Trinkets 3.4.2
-Cammies backpacks 2.13
-CreativeCore-lib
-Item Physic 1.6.6
-Combat roll 1.1.4
-Campanion 4.1.2
-Cem 0.7.1 (Fresh animations dependency)
-Exordium 1.0.2
-Onebar 3.3.4
-Alloygery 2.5.1
-Not Enough Animations 1.6.2
-Female Gender Mod 3.0.1
-Smooth Swapping 0.6
-Firstperson 2.2.2 (dependency for something)
-Player Animator lib
-Better Combat 1.6.1
-Sound Physics 1.0.18
-MCA 7.4.7
-Durability Viewer 0.58.5
-Journeymap 5.9.3
-Presence Footsteps 1.6.4
-Architectury lib
-REI 9.1.591
-MoreCulling 0.16.0
-Midnight lib
-CullLeaves 3.0.1
-3D Skin Layers
-lambdynamiclights

-Sodium Lithium and iris + more performance mods`

**Comment by CleverNucleus** [comment] 2023-03-12 13:36
Hi there,
I appreciate the mod list - let me know if you find the incompatibility.
Thanks.

**Comment by Resulon12** [comment] 2023-04-09 04:27
I had the same issue but could not find any incompatibilities. The game freezes on "joining world" even on newly created worlds. All I noticed was in my Task manager my CPU was throwing a fit, basically using 100% and everything on my pc would either slow down or stutter. Removing the mod fixed it and everything works perfectly fine now. But again, no incompatibilities found throuh testing.

**Comment by CleverNucleus** [comment] 2023-04-09 11:18
@Resulon12 just to be clear, this is happening with *just* PlayerEx, Data Attributes and Fabric API installed?

**Comment by PixelatedBruh** [comment] 2023-05-01 11:39
I would like to say its lithium that causes this and it is whenever you change your modlist without removing data attributes and lithium. example have them already installed and then add another mod to your list (doesnt matter what mod) will cause the game to freeze loading a world

**Comment by CleverNucleus** [comment] 2023-05-01 11:49
On review, I think the issue is likely a duplicate of [this](https://github.com/CleverNucleus/data-attributes/issues/80) on Data Attributes. I've said it there, but I cannot seem to replicate this behaviour.

I'm closing this issue now based on it being a duplicate as aforementioned - not that the issue is solved 🙃

**Closed by CleverNucleus** 2023-05-01 11:49 UTC
Labels: question
